/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.ChefRole;

import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Donation.DonationDirectory;
import Business.EcoSystem;
import Business.Menu.MenuDirectory;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.RestaurantTable.RestaurantTableDirectory;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nirmitipatil
 */
public class ChefWorkAreaJPanel extends javax.swing.JPanel {

    /** Creates new form ChefWorkAreaJPanel */
    private JPanel userProcessContainer; 
    private UserAccount account; 
    private EcoSystem business; 
    private CustomerDirectory customerDirectory; 
    private RestaurantDirectory restaurantDirectory; 
    private DeliveryManDirectory deliveryManDirectory; 
    private MenuDirectory menuDirectory;
    private OrderDirectory orderDirectory; 
    private RestaurantTableDirectory RestaurantTableDirectory;
    private DonationDirectory donationDirectory;
    private SupplierDirectory supplierDirectory;
    
    

    public ChefWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, CustomerDirectory customerDirectory, RestaurantDirectory restaurantDirectory, DeliveryManDirectory deliveryManDirectory, MenuDirectory menuDirectory, OrderDirectory orderDirectory, RestaurantTableDirectory restaurantTableDirectory, DonationDirectory donationDirectory, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer; 
        this.account = account; 
        this.business = business; 
        this.customerDirectory = customerDirectory; 
        this.restaurantDirectory = restaurantDirectory; 
        this.deliveryManDirectory = deliveryManDirectory; 
        this.menuDirectory = menuDirectory;
        this.orderDirectory = orderDirectory; 
        this.RestaurantTableDirectory = RestaurantTableDirectory;
        this.donationDirectory = donationDirectory;
        this.supplierDirectory = supplierDirectory;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ChefWorkAreaTable = new javax.swing.JTable();
        AssignDishes = new javax.swing.JButton();
        Processed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChefWorkAreaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Dishes", "Assign", "Duration", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ChefWorkAreaTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 101, 565, 165));

        AssignDishes.setText("Assign to Self");
        AssignDishes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignDishesActionPerformed(evt);
            }
        });
        add(AssignDishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 302, -1, -1));

        Processed.setText("Processed");
        Processed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessedActionPerformed(evt);
            }
        });
        add(Processed, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 302, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Assign Dishes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 27, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AssignDishesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignDishesActionPerformed
        // TODO add your handling code here:
        
        /*int selectedRow = ChefWorkAreaTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) ChefWorkAreaTable.getModel();
        
        
        ArrayList<Order> order = null;
        DeliveryMan get = null;
        for(int i=0;i<business.getDeliveryManDirectory().getDeliverymanList().size();i++){
        if(business.getDeliveryManDirectory().getDeliverymanList().get(i).getName().equals(userAccount.getEmployee().getName())){
            get = business.getDeliveryManDirectory().getDeliverymanList().get(i);
        }
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Atleast one row should be selected");
            return;
        }else{
            String name = model.getValueAt(selectedRow, 0).toString();
            
            for(int i=0;i<get.getOrder().size();i++){
            if(get.getOrder().get(i).getOrderID().equals(name)){
                get.getOrder().get(i).setOrderstatus("Assigned to Self");
                order = get.getOrder().get(i).getCustomer().getOrder();
               

            }
        }
            for(int j=0;j<order.size();j++){
                if(order.get(j).getOrderID().equals(name)){
                    order.get(j).setOrderstatus("Assigned to Self");
                }
            }

        }
        
        populateDeliveryManOrders();*/
    }//GEN-LAST:event_AssignDishesActionPerformed

    private void ProcessedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessedActionPerformed
        // TODO add your handling code here:
        
        /*int selectedRow = ChefWorkAreaTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) ChefWorkAreaTable.getModel();
        
        Order current = null;
        ArrayList<Order> order = null;
        DeliveryMan get = null;
        for(int i=0;i<business.getDeliveryManDirectory().getDeliverymanList().size();i++){
        if(business.getDeliveryManDirectory().getDeliverymanList().get(i).getName().equals(userAccount.getEmployee().getName())){
            get = business.getDeliveryManDirectory().getDeliverymanList().get(i);
        }
        }
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Atleast one row should be selected");
            return;
        }else{
            String name = model.getValueAt(selectedRow, 0).toString();
            for(int i=0;i<get.getOrder().size();i++){
            if(get.getOrder().get(i).getOrderID().equals(name)){
                current = get.getOrder().get(i);
                get.getOrder().get(i).setOrderstatus("Ready to Serve");
                order = get.getOrder().get(i).getCustomer().getOrder();

            }
        }
            for(int j=0;j<order.size();j++){
                if(order.get(j).getOrderID().equals(name)){
                    order.get(j).setOrderstatus("Ready to Serve");
                }
            }
        }
        populateDeliveryManOrders();*/
    }//GEN-LAST:event_ProcessedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignDishes;
    private javax.swing.JTable ChefWorkAreaTable;
    private javax.swing.JButton Processed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
