
package userinterface.SystemAdminWorkArea;

import Business.Chef.ChefDirectory;
import Business.Customer.Customer;
import Business.EcoSystem;

import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Donation.DonationDirectory;
import Business.Insurance.InsuranceDirectory;

import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Server.ServerDirectory;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Talre
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

   
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CustomerDirectory customerDirectory;
    RestaurantDirectory restaurantDirectory;
    DeliveryManDirectory deliveryManDirectory;
    ChefDirectory chefDirectory;
    ServerDirectory serverDirectory;
    UserAccount account;
    DonationDirectory donationDirectory;
    SupplierDirectory supplierDirectory; 
    InsuranceDirectory insuranceDirectory;
    


    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem, CustomerDirectory customerDirectory, RestaurantDirectory restaurantDirectory, DeliveryManDirectory deliveryManDirectory,ChefDirectory chefDirectory, ServerDirectory serverDirectory, DonationDirectory donationDirectory, SupplierDirectory supplierDirectory) {
    
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.customerDirectory = ecosystem.getCustomerDirectory();
        this.deliveryManDirectory = ecosystem.getDeliveryManDirectory();
        this.restaurantDirectory = ecosystem.getRestaurantDirectory();
        this.chefDirectory = ecosystem.getChefDirectory();
        this.serverDirectory = ecosystem.getServerDirectory();
        this.donationDirectory = ecosystem.getDonationDirectory();
        this.supplierDirectory = ecosystem.getSupplierDirectory();
        this.insuranceDirectory = ecosystem.getInsuranceDirectory();

        populateTree();
        
        }

    public void populateTree() {
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

       
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Admin");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        ArrayList<Customer> customerList = ecosystem.getCustomerDirectory().getCustomerDirectory();
        ArrayList<DeliveryMan> deliveryList = ecosystem.getDeliveryManDirectory().getDeliveryManDirectory();
        ArrayList<Restaurant> restaurantList = ecosystem.getRestaurantDirectory().getRestaurantDirectory();

        Customer customer;
        DeliveryMan deliveryMan;
        Restaurant restaurant;

        DefaultMutableTreeNode customerListNode = new DefaultMutableTreeNode("Customers");
        DefaultMutableTreeNode deliveryManListNode = new DefaultMutableTreeNode("Delivery Man");
        DefaultMutableTreeNode restaurantListNode = new DefaultMutableTreeNode("Restaurants");
        networks.insert(customerListNode, 0);
        networks.insert(deliveryManListNode, 1);
        networks.insert(restaurantListNode, 2);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;

        for (int i = 0; i < customerList.size(); i++) {
            customer = customerList.get(i);
            networkNode = new DefaultMutableTreeNode(customer.getName());
            customerListNode.insert(networkNode, i);

        }
        for (int j = 0; j < deliveryList.size(); j++) {
            deliveryMan = deliveryList.get(j);
            enterpriseNode = new DefaultMutableTreeNode(deliveryMan.getName());
            deliveryManListNode.insert(enterpriseNode, j);
        }

        for (int k = 0; k < restaurantList.size(); k++) {
            restaurant = restaurantList.get(k);
            organizationNode = new DefaultMutableTreeNode(restaurant.getRestaurantName());
            restaurantListNode.insert(organizationNode, k);
        }

        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();
        btnRestaurant = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnDonations = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnSuppliers1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(200);
        jSplitPane.setDividerSize(2);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EXPLORER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Optima", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        jLabel1.setText("Selected Node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 25, -1, -1));

        lblSelectedNode.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        lblSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 29, -1, -1));

        btnCustomer.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnCustomer.setText("Manage All Customers");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 413, 39));

        btnRestaurant.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnRestaurant.setText("Manage Restaurants");
        btnRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantActionPerformed(evt);
            }
        });
        jPanel2.add(btnRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 413, 41));

        btnDelivery.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDelivery.setText("Manage Delivery Persons");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 413, 41));

        btnDonations.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnDonations.setText("Manage Donations");
        btnDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationsActionPerformed(evt);
            }
        });
        jPanel2.add(btnDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, 413, 41));

        btnSuppliers.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSuppliers.setText("Manage Suppliers");
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, 413, 43));

        btnSuppliers1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSuppliers1.setText("Manage Insurance");
        btnSuppliers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliers1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuppliers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 307, 413, 41));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed

        ManageCustomerJPanel mCustJPnl = new ManageCustomerJPanel(userProcessContainer, ecosystem, customerDirectory);
        userProcessContainer.add("ManageCustomersJPanel", mCustJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantActionPerformed
        ManageRestaurantJPanel mRestJPnl = new ManageRestaurantJPanel(userProcessContainer, account, ecosystem, restaurantDirectory, serverDirectory);
        userProcessContainer.add("ManageRestaurantJPanel", mRestJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRestaurantActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        ManageDeliveryManJPanel mDMJPnl = new ManageDeliveryManJPanel(userProcessContainer, ecosystem, deliveryManDirectory);
        userProcessContainer.add("ManageDeliveryManJPanel", mDMJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged

        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            lblSelectedNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged

    private void btnDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationsActionPerformed
        // TODO add your handling code here:
        ManageDonationJPanel mDonJPnl = new ManageDonationJPanel(userProcessContainer, account, ecosystem, restaurantDirectory, serverDirectory, donationDirectory);
        userProcessContainer.add("ManageRestaurantJPanel", mDonJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnDonationsActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        // TODO add your handling code here:
        ManageSupplierJPanel mSupJPnl = new ManageSupplierJPanel(userProcessContainer, account, ecosystem, restaurantDirectory, serverDirectory, supplierDirectory);
        userProcessContainer.add("ManageRestaurantJPanel", mSupJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnSuppliers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliers1ActionPerformed
        // TODO add your handling code here:
        ManageInsuranceJPanel mInsuranceJPnl = new ManageInsuranceJPanel(userProcessContainer, account, ecosystem);
        userProcessContainer.add("ManageRestaurantJPanel", mInsuranceJPnl);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSuppliers1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnDonations;
    private javax.swing.JButton btnRestaurant;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btnSuppliers1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
