/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Donation.DonatedItem;
import Business.Donation.Donation;
import Business.Donation.DonationDirectory;
import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Menu.MenuDirectory;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.RestaurantTable.RestaurantTableDirectory;
import Business.Server.ServerDirectory;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harshit
 */
public class ManageDonationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private RestaurantDirectory restaurantDirectory;
    private Restaurant restaurant;
    private MenuDirectory menuDirectory;
    private RestaurantTableDirectory restaurantTableDirectory;
    private DonationDirectory donationDirectory;

    /**
     * Creates new form ManageDonationJPanel
     */
    public ManageDonationJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, RestaurantDirectory restaurantDirectory, MenuDirectory menuDirectory, RestaurantTableDirectory restaurantTableDirectory, DonationDirectory donationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        this.menuDirectory = ecoSystem.getMenuDirectory();
        this.restaurantTableDirectory = ecoSystem.getRestaurantTableDirectory();
        this.donationDirectory = ecoSystem.getDonationDirectory();
        valueLabel.setText(account.getEmployee().getName());
        populateTable();
        populateRestaurantCombo();
        
    
        
    }
        public void populateRestaurantCombo() {
        boxNgo.removeAllItems();
        boxNgo.addItem("  ");
        for(Donation donation : ecoSystem.getDonationDirectory().getDonationDirectory()) {
            //System.out.println("res" + res);
            boxNgo.addItem(donation.getDonationName());
        }
        }
    public void populateTable() {
        DefaultTableModel dTableModel = (DefaultTableModel) tblItem.getModel();
        dTableModel.setRowCount(0);
//        String restaurantName = boxRestaurant.getSelectedItem().toString();
        
        String restaurantName = account.getEmployee().getName();
        Restaurant restaurant = ecoSystem.getRestaurantDirectory().getRestaurant(restaurantName);
        for(Menu menu : ecoSystem.getMenuDirectory().getMenuDirectory()){
            if(restaurantName.equals(menu.getRestaurantName())) {
                Object [] row = new Object[1];
                row[0] = menu;
                dTableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        boxNgo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        lblModelName = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnMenuShow1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseLabel.setFont(new java.awt.Font("Optima", 1, 18)); // NOI18N
        enterpriseLabel.setText("Restaurant Name:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 61, 160, 30));

        valueLabel.setBackground(new java.awt.Color(255, 204, 153));
        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 61, 210, 30));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Donation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Optima", 1, 14)); // NOI18N
        enterpriseLabel1.setText("Select who to donate: ");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 103, 154, 30));

        boxNgo.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        boxNgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxNgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNgoActionPerformed(evt);
            }
        });
        add(boxNgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 106, 214, -1));

        tblItem.setBackground(new java.awt.Color(204, 204, 204));
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Item Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 159, 525, 170));

        lblModelName.setBackground(new java.awt.Color(255, 255, 255));
        lblModelName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblModelName.setText("Item Name");
        add(lblModelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 347, 86, 20));

        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemNameKeyReleased(evt);
            }
        });
        add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 347, 120, -1));

        lblManufacturer.setBackground(new java.awt.Color(255, 255, 255));
        lblManufacturer.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblManufacturer.setText("Quantity");
        add(lblManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 389, 84, -1));

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 385, 122, -1));

        btnMenuShow1.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuShow1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnMenuShow1.setText("Donate");
        btnMenuShow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuShow1ActionPerformed(evt);
            }
        });
        add(btnMenuShow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 347, 110, 51));
    }// </editor-fold>//GEN-END:initComponents

    private void boxNgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNgoActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex = tblItem.getSelectedRow();
        
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        
        
        
        DefaultTableModel model = (DefaultTableModel) tblItem.getModel();
        Menu selectedItem = (Menu)model.getValueAt(selectedRowIndex, 0);
        
        txtItemName.setText(selectedItem.getItemName());
        txtQty.setText("0");
        
        
        
    }//GEN-LAST:event_tblItemMouseClicked

    private void txtItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtItemNameKeyReleased

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtQtyKeyReleased

    private void btnMenuShow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuShow1ActionPerformed

        int quantity = 0;
        try {
            quantity = Integer.parseInt(txtQty.getText());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Quantity must have 0-9 integers only");
            return;
        }
        
        String itemName = txtItemName.getText();
        
        String restaurantName = account.getEmployee().getName();
        
        
        if(itemName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please select a item to donate. :) ");
            return;
        }
        else if(quantity <= 0){
            JOptionPane.showMessageDialog(null, "Please donate atleast 1 item :) ");
            return;
        }
        else if(boxNgo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a NGO.");
            return;
        }
        else{
            for (Menu menu: ecoSystem.getMenuDirectory().getMenuDirectory()){
                if(menu.getRestaurantName().equals(restaurantName)){
                    if(menu.getItemName() == itemName){
                        for(Donation donation : ecoSystem.getDonationDirectory().getDonationDirectory()){
                            if(donation.getDonationName().equals(boxNgo.getSelectedItem().toString())){
                                DonatedItem ditem = new DonatedItem(itemName, account.getEmployee().getName(), quantity);
                                donation.getDonationList().add(ditem);
                            }
                        }
                        JOptionPane.showMessageDialog(null, "Thanks for the donation. We appreciate your consideration.");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Item name does not exist in the menu. Please select an appropriate item.");
                    }
                }
            }

        }
        
    }//GEN-LAST:event_btnMenuShow1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNgo;
    private javax.swing.JButton btnMenuShow1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelName;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
