/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.HeadChef.HeadChefDirectory;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Server.ServerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.HeadChefRole.CreateHeadChefJPanel;
import userinterface.ServerRole.CreateServerJPanel;

/**
 *
 * @author talre
 */
public class ManageHeadChefJPanel extends javax.swing.JPanel {
    
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private RestaurantDirectory restaurantDirectory;
    private ServerDirectory serverDirectory;
    private HeadChefDirectory headChefDirectory;
    private Restaurant restaurant;
    
    /**
     * Creates new form ManageHeadChefJPanel
     */
    public ManageHeadChefJPanel() {
        
    }

    ManageHeadChefJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, RestaurantDirectory restaurantDirectory, HeadChefDirectory headChefDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.serverDirectory = ecoSystem.getServerDirectory();
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        this.headChefDirectory = ecoSystem.getHeadChefDirectory();
        populateTable();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        createHeadChef = new javax.swing.JButton();
        modifyHeadChef = new javax.swing.JButton();
        deleteHeadChef = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Name ", "Email Address", "Address", "Mobile Number", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 637, 132));

        jLabel1.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Head Chef");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 657, -1));

        createHeadChef.setText("Create Head Chef");
        createHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeadChefActionPerformed(evt);
            }
        });
        add(createHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 262, -1, -1));

        modifyHeadChef.setText("Modify HeadChef");
        modifyHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyHeadChefActionPerformed(evt);
            }
        });
        add(modifyHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 262, -1, -1));

        deleteHeadChef.setText("Delete Head Chef");
        deleteHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHeadChefActionPerformed(evt);
            }
        });
        add(deleteHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 262, -1, -1));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeadChefActionPerformed
    CreateHeadChefJPanel createHeadChefJPanel = new CreateHeadChefJPanel(userProcessContainer,account, ecoSystem, restaurantDirectory, headChefDirectory);
        userProcessContainer.add("CreateHeadChefJPanel",createHeadChefJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHeadChefActionPerformed

    private void modifyHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyHeadChefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyHeadChefActionPerformed

    private void deleteHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHeadChefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteHeadChefActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton createHeadChef;
    private javax.swing.JButton deleteHeadChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyHeadChef;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        }
}
