/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;


import Business.HeadChef.HeadChef;
import Business.EcoSystem;
import Business.HeadChef.HeadChefDirectory;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Server.ServerDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HeadChefRole.CreateHeadChefJPanel;
import userinterface.HeadChefRole.ModifyHeadChefJPanel;
import userinterface.ServerRole.CreateServerJPanel;

/**
 *
 * @author talre
 */
public class ManageHeadChefJPanel extends javax.swing.JPanel {
    
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private RestaurantDirectory restaurantDirectory;
    private ServerDirectory serverDirectory;
    private HeadChefDirectory headChefDirectory;
    private Restaurant restaurant;
    
    /**
     * Creates new form ManageHeadChefJPanel
     */
    
    ManageHeadChefJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, RestaurantDirectory restaurantDirectory, HeadChefDirectory headChefDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.serverDirectory = ecoSystem.getServerDirectory();
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        this.headChefDirectory = ecoSystem.getHeadChefDirectory();
        populateTable();
        }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblHeadchef.getModel();
        dtm.setRowCount(0);
        String restaurantName = account.getEmployee().getName();
        
        for(HeadChef headchef : ecoSystem.getHeadChefDirectory().getHeadChefDirectory()){
            
            if(headchef.getRestaurantName().equals(restaurantName)){
                Object [] row = new Object[6];
                row[0] = headchef;
                row[1] = headchef.getName();
                row[2] = headchef.getEmail();
                row[3] = headchef.getHomeAddress();
                row[4] = headchef.getPhoneNumber();
                row[5] = headchef.getAge();
                dtm.addRow(row);
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHeadchef = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        createHeadChef = new javax.swing.JButton();
        modifyHeadChef = new javax.swing.JButton();
        deleteHeadChef = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHeadchef.setBackground(new java.awt.Color(204, 204, 204));
        tblHeadchef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Name ", "Email Address", "Address", "Mobile Number", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHeadchef);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 637, 132));

        jLabel1.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Head Chef");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, -1));

        createHeadChef.setBackground(new java.awt.Color(255, 255, 255));
        createHeadChef.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        createHeadChef.setText("Create Head Chef");
        createHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeadChefActionPerformed(evt);
            }
        });
        add(createHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 50));

        modifyHeadChef.setBackground(new java.awt.Color(255, 255, 255));
        modifyHeadChef.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        modifyHeadChef.setText("Modify HeadChef");
        modifyHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyHeadChefActionPerformed(evt);
            }
        });
        add(modifyHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 180, 50));

        deleteHeadChef.setBackground(new java.awt.Color(255, 255, 255));
        deleteHeadChef.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        deleteHeadChef.setText("Delete Head Chef");
        deleteHeadChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHeadChefActionPerformed(evt);
            }
        });
        add(deleteHeadChef, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 170, 50));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        refreshJButton1.setBackground(new java.awt.Color(153, 255, 153));
        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });
        add(refreshJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeadChefActionPerformed
    CreateHeadChefJPanel createHeadChefJPanel = new CreateHeadChefJPanel(userProcessContainer,account, ecoSystem, restaurantDirectory, headChefDirectory);
        userProcessContainer.add("CreateHeadChefJPanel",createHeadChefJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHeadChefActionPerformed

    private void modifyHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyHeadChefActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHeadchef.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HeadChef headchef = (HeadChef)tblHeadchef.getValueAt(selectedRow, 0);
        ModifyHeadChefJPanel modifyHeadChef = new ModifyHeadChefJPanel(userProcessContainer, ecoSystem, headChefDirectory, headchef);
        userProcessContainer.add("ModifyHeadChefJPanel", modifyHeadChef);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_modifyHeadChefActionPerformed

    private void deleteHeadChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHeadChefActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHeadchef.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        HeadChef headchef = (HeadChef) tblHeadchef.getValueAt(selectedRow, 0);
        headChefDirectory.removeHeadChef(headchef);
        populateTable();
    }//GEN-LAST:event_deleteHeadChefActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton createHeadChef;
    private javax.swing.JButton deleteHeadChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyHeadChef;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JTable tblHeadchef;
    // End of variables declaration//GEN-END:variables

}
