/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HeadChefRole;

import Business.Chef.ChefDirectory;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.HeadChef.HeadChefDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.RestaurantAdminRole.ModifyServerJPanel;

/**
 *
 * @author talre
 */
public class HeadChefWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeadChefWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    UserAccount account;
    private EcoSystem ecoSystem;
    private RestaurantDirectory restaurantDirectory;
    private HeadChefDirectory headChefDirectory;
    private ChefDirectory chefDirectory;
    
    
    public HeadChefWorkAreaJPanel() {
        
    }

    public HeadChefWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, RestaurantDirectory restaurantDirectory,HeadChefDirectory headChefDirectory, ChefDirectory chefDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.restaurantDirectory = ecoSystem.getRestaurantDirectory();
        this.headChefDirectory = ecoSystem.getHeadChefDirectory();
        this.chefDirectory = ecoSystem.getChefDirectory();
        
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageChefButton = new javax.swing.JButton();
        manageMenuButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 37, 189, 41));

        manageChefButton.setText("Manage Chefs");
        manageChefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageChefButtonActionPerformed(evt);
            }
        });
        add(manageChefButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 148, 185, -1));

        manageMenuButton.setText("Manage Menu ingredients");
        manageMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuButtonActionPerformed(evt);
            }
        });
        add(manageMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 148, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageChefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageChefButtonActionPerformed
        ManageChefJPanel mchp = new ManageChefJPanel(userProcessContainer, account, ecoSystem, restaurantDirectory, headChefDirectory, chefDirectory);
        userProcessContainer.add("ManageChefJPanel", mchp);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageChefButtonActionPerformed

    private void manageMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageChefButton;
    private javax.swing.JButton manageMenuButton;
    // End of variables declaration//GEN-END:variables
}
